app1/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.home),
]

core/urls.py
from django.conf.urls import url
from core import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^events$', views.all_events, name='events'),
    # url(r'^events/(?P<slug>[-\w]+)/$', views.EventDetailView.as_view(), name='article-detail'),
    # url(r'^events/(?P<slug>[-\w]+)/$', views.EventDetailView.as_view(), name='article-detail'),
    # url(r'^event/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<slug>[-\w]+)/$',
    #     views.EventDetailView.as_view(), name='article-detail'),
    url(r'^event/(?P<pk>\d+)/(?P<slug>[-\w]+)/$',
        views.EventDetailView.as_view(), name='event-detail'),
    url(r'^org/(?P<slug>[-\w]+)/$',
        views.OrgDetailView.as_view(), name='org-detail'),
    url(r'^organizers/$', views.OrgsList.as_view(), name='organizers'),
    url(r'^org-reg/', views.registerOrg, name='org-reg'),
    url(r'^event-reg/', views.eventReg, name='event-reg'),
    url(r'^dashboard/', views.dashboardEventList, name='dashboard'),
    url(r'^account/', views.account , name='account'),
    url(r'^event-edit/(?P<id>[0-9]+)/', views.eventEdit, name='event-edit'),
    url(r'^org-update/', views.orgProfileUpdate, name='org-update'),
]

prj3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

#ckeditor import
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'', include('core.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^letters/', include('letters.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from django.conf import settings

from ckeditor_uploader.fields import RichTextUploadingField
from autoslug import AutoSlugField

class Org(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    orgname = models.CharField(max_length=150, null=False, blank=False)
    slug = AutoSlugField(populate_from='orgname',null=True, blank=True, unique=True)
    logo = models.ImageField(upload_to='uploads/org/logos/', null=True, blank=True)
    qr = models.ImageField(upload_to='uploads/org/qrs/', null=True, blank=True )
    location_cn = models.CharField(max_length=200, null=True, blank=True)
    location_en = models.CharField(max_length=200, null=True, blank=True)
    about_en = models.TextField(null=True, blank=True)
    about_cn = models.TextField(null=True, blank=True)
    richcontent = RichTextUploadingField(null=True, blank=True)


    # i guess this block is not needed anymore, since AutoSlug installed
    # but leave it for now, just in a case

    # def save(self, *args, **kwargs):
    #     if not self.id:
    #         self.slug = slugify(self.orgname)
    #         super(Org, self).save(*args, **kwargs)

    def __str__(self):
        return self.orgname

    def get_absolute_url(self):
        return reverse('org-detail', kwargs={'slug': self.slug})


class Event(models.Model):
    REGIONS = (
        ('Ns', '南山Nanshan'),
        ('Ft', '福田Futian'),
        ('Lh', '罗湖Luohu'),
        ('Lg', '龙岗Longgang'),
        ('Bn', '宝安Baoan'),
    )
    author = models.ForeignKey(User, null=True, blank=True, related_name="author")
    org = models.ForeignKey(Org, null=True, blank=True)
    title = models.CharField(max_length=150, null=False, blank=False)
    slug = AutoSlugField(populate_from='title',null=True, blank=True, unique=True)
    title_cn = models.CharField(max_length=150, null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    start_time = models.TimeField(null=True, blank=True)
    district = models.CharField(max_length=2,choices=REGIONS, null=False, blank=False)
    fee = models.DecimalField(max_digits=4, decimal_places=0,null=True, blank=True )
    location_cn = models.CharField(max_length=200, null=True, blank=False)
    location_en = models.CharField(max_length=200, null=True, blank=False)
    content_en = models.TextField(null=True, blank=True)
    content_cn = models.TextField(null=True, blank=True)
    richcontent = RichTextUploadingField(null=True, blank=True)
    is_published = models.BooleanField(null=False, blank=False, default=False)
    thumbnail = models.ImageField('thumbnail', upload_to='uploads/event_thumbnails/', null=True, blank=True)
    wechat_qr= models.ImageField('qr',upload_to='uploads/wechat_qr-s/', null=True, blank=True)

    class Meta:
        ordering = ['-start_date']
        verbose_name_plural = "Events"
    
    # i guess this block is not needed anymore, since AutoSlug installed
    # but leave it for now, just in a case
    # def save(self, *args, **kwargs):
    #     if not self.id:
    #         self.slug = slugify(self.title)
    #     super(Event, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('event-detail', kwargs={'slug': self.slug,
                                                 'pk': self.pk,})

core/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Org, Event
from django.contrib.admin.widgets import AdminDateWidget
from django.core.exceptions import ValidationError
from crispy_forms.helper import FormHelper
from ckeditor.widgets import CKEditorWidget

class OrgForm(forms.ModelForm):
    about_en = forms.CharField(
                    help_text='<i>short inro about organizer </i>', 
                    widget=forms.Textarea(attrs={'rows': 3}))
    about_cn = forms.CharField(
                    help_text='<i>项目介绍 </i>', 
                    widget=forms.Textarea(attrs={'rows': 3}))
    richcontent = forms.CharField(
                    widget=CKEditorWidget(attrs={'cols':50,'rows': 3}),
                    help_text="""^^^ more details about your project,
                    put pictures, tables,
                    files whatever you want for introducing your project"""
                    )

    class Meta:
        model = Org
        widgets = {'user': forms.HiddenInput()}
        exclude = ['slug']

    # user = models.ForeignKey(User, null=True, blank=True) 
    # orgname = models.CharField(max_length=150, null=False, blank=False)
    # slug = models.SlugField(max_length=150, unique=True, verbose_name='slug', null=True, blank=True)
    # logo = models.ImageField(upload_to='uploads/org/logos/', null=True, blank=True)
    # qr = models.ImageField(upload_to='uploads/org/qrs/', null=True, blank=True )
    # moto = models.CharField(max_length=200, null=True, blank=True)
    # location_cn = models.CharField(max_length=200, null=True, blank=True)
    # location_en = models.CharField(max_length=200, null=True, blank=True)


class EventForm(forms.ModelForm):
    #sectors
    start_date = forms.DateField(widget=forms.SelectDateWidget())
    start_time = forms.TimeField(
                    widget=forms.TextInput(attrs={'size': 5}),
                    initial="19:11",
                    help_text='<i> "hh:mm" format</i>',)
    fee = forms.DecimalField(
                    initial=None,
                    help_text='<i>if event is Free, paste 0 </i>',)
    content_en = forms.CharField(
                    help_text='<i>short info for notifications ans stuff </i>', 
                    widget=forms.Textarea(attrs={'rows': 3}))
    content_cn = forms.CharField(
                    help_text='<i>in CN , short info for notifications ans stuff </i>', 
                    widget=forms.Textarea(attrs={'rows': 3}))
    richcontent = forms.CharField(widget=CKEditorWidget(attrs={'cols':50,'rows': 3}))

    class Meta:
        model = Event
        widgets = {'author': forms.HiddenInput(),
                    'org': forms.HiddenInput(),
                    }
        
        fields = ("__all__")
    
    # i guess this block is not needed anymore, since AutoSlug installed
    # but leave it for now, just in a case
    # def clean_slug(self):
    #         data = self.cleaned_data['slug']
    #         if Event.objects.filter(slug=data).exists():
    #             raise ValidationError("this slug exists")
    #         return data


class EventUpdateForm(forms.ModelForm):
    #sectors
    start_date = forms.DateField(widget=forms.SelectDateWidget())
    start_time = forms.TimeField(
                    widget=forms.TextInput(attrs={'size': 5}),
                    initial="19:11",
                    help_text='<i> "hh:mm" format</i>',)
    fee = forms.DecimalField(
                    initial=None,
                    help_text='<i>if event is Free, paste 0 </i>',)
    content_en = forms.CharField(
                    help_text='<i>short info for notifications ans stuff </i>', 
                    widget=forms.Textarea(attrs={'rows': 3}))
    content_cn = forms.CharField(
                    help_text='<i>in CN , short info for notifications ans stuff </i>', 
                    widget=forms.Textarea(attrs={'rows': 3}))
    richcontent = forms.CharField(widget=CKEditorWidget(attrs={'cols':50,'rows': 3}))

    class Meta:
        model = Event
        widgets = {'author': forms.HiddenInput(),
                    'org': forms.HiddenInput(),
                    }
        
        fields = ("__all__")


class OrgUpdateForm(forms.ModelForm):
    orgname = forms.CharField(disabled=True)
    about_en = forms.CharField(help_text='<i>short info about organizer </i>')
    class Meta:
        model = Org
        exclude = ['user']

core/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404,HttpResponseNotFound
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.urlresolvers import reverse

from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.core.exceptions import ObjectDoesNotExist

from .models import *
from .forms import OrgForm, EventForm, EventUpdateForm, OrgUpdateForm

def index(request):
    user = request.user
    org=None
    try:
        org = Org.objects.get(user_id=request.user.id)
    except Exception:
        pass
    upcoming_events = Event.objects.filter(is_published=True, start_date__gte=timezone.now()).order_by('start_date')
    past_events = Event.objects.filter(is_published=True, start_date__lt=timezone.now()).order_by('-start_date')

    return render(request, 'core/index.html', {
        'upcoming_events': upcoming_events,
        'past_events': past_events,
        'user': user,
        'org': org,
    })


def all_events(request):

    upcoming_events = Event.objects.filter(is_published=True, start_date__gte=timezone.now()).order_by('start_date')
    past_events = Event.objects.filter(is_published=True, start_date__lt=timezone.now()).order_by('-start_date')

    return render(request, 'core/events.html', {
        'upcoming_events': upcoming_events,
        'past_events': past_events,
    })


class EventDetailView(DetailView):

    model = Event

    def event_detail_view_func(request, slug):
        event = Event.objects.get(slug=slug)
        context_dict = {
            'event':event
        }
        return render(request, 'core/event_detail.html', context_dict)


class OrgDetailView(DetailView):

    model = Org

    def org_detail_view_func(request, slug):
        org = Org.objects.get(slug=slug)
        context_dict = {
            'org': org
        }
        return render(request, 'core/org_detail.html', context_dict)


class OrgsList(ListView):
    model = Org
    context_object_name = 'orgs'
    template_name = 'organizers.html'


@login_required
def registerOrg(request):
    if request.user.groups.filter(name='Organizers').exists():
        return HttpResponseNotFound("You are already an organizer") 
    else:
        if request.method == "POST":
            org_form = OrgForm(data=request.POST)
            if org_form.is_valid():
                org = org_form.save(commit=False)
                org.user = request.user
                org.save()
                g = Group.objects.get(name='Organizers') 
                g.user_set.add(request.user)
                return HttpResponseRedirect(reverse('org-update'))
                # else:
                #     return HttpResponse("No website")
            else:
                print(org_form.errors)
        else:
            org_form = OrgForm()
        return render(request, 'core/org-reg.html', {
                            'org_form': org_form,
                            })


@login_required
def eventReg(request):
    #ToDo should be done with property
    if request.user.groups.filter(name="Organizers").exists(): # <<<
        if request.method == "POST":
            event_form = EventForm(request.POST or None, request.FILES or None)
            if event_form.is_valid():
                event = event_form.save(commit=False)
                event.author = request.user
                event.org = Org.objects.get(user_id=request.user.id)
                event.thumbnail = event_form.cleaned_data['thumbnail'] 
                event.wechat_qr = event_form.cleaned_data['wechat_qr'] 
                event.save()
                return HttpResponseRedirect(reverse("dashboard"))
            else:
                print(event_form.errors)
        else:
            event_form = EventForm()
        return render(request, 'core/event-reg.html',
                                {'event_form': event_form,})
    else:
        return HttpResponse(
            "You are not the organizer yet.\
            Please go to Account >> Org Register"
            )

@login_required
def dashboardEventList(request):
    user = request.user
    events = Event.objects.filter(author=request.user) #self.rquest.user
    return render (request, 'core/dashboard.html',
                             {"events":events,})

@login_required
def account(request):
    is_org = False
    try:
        current_org = Org.objects.get(user_id=request.user.id)
    except Exception:
        pass
    if request.user.groups.filter(name="Organizers").exists():
        is_org = True
    return render (request, 'core/account.html',locals())

@login_required
def eventEdit(request, id):
    event = get_object_or_404(Event, id=id)
    if event.author == request.user:
        form = EventUpdateForm(request.POST or None, request.FILES or None, instance=event)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("dashboard"))
        else:
            print(form.errors)
        return render(request, 'core/event-edit.html', {
                                'form': form,
                                })
    else:
        return HttpResponseNotFound("\
            <h1>Page not found</h1>\
            <p>Event doesn't exist, or you are not the authour of it</p>\
            <p>Meanwile if you are the author, please contact support</p>"\
            )


@login_required
def orgProfileUpdate(request):
    org = get_object_or_404(Org, id= Org.objects.get(user=request.user).id)
    if request.user.groups.filter(name="Organizers").exists():
        org_form = OrgUpdateForm(request.POST or None, request.FILES or None, instance=org)
        if org_form.is_valid():
            org_v = org_form.save(commit=False)
            org_v.logo = org_form.cleaned_data['logo'] 
            org_v.qr = org_form.cleaned_data['qr']
            org_v.save()
            return HttpResponseRedirect(reverse('account'))
        else:
            print(org_form.errors)
            return render (request, 'core/org_update.html',
                                     {"org_form":org_form,
                                     })
    else:
        return HttpResponse(
            "You are not the organizer yet.\
            Please go to Account >> Org Register"
            )
 

core/templates/core/account.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="container">
	<div class="alert alert-warning" role="alert">
		<h4 style="margin-top: 0">Thank you for using SzMakers.com </h4>
		<p>Please keep in mind, that project is in developing stage, and ment to be OpenSource .</p>
		<p>So please feel free to conteact developer(s) to help us make the app better </p>
	</div>
</div>

<br>
<br>
<br>

<div class="container">
	<div class ="col-sm-3 col-xs-6 text-center">
		<a href="{% url 'auth_logout' %}" class="btn btn-danger" role="button">LogOut</a></p>
		<p>Log out of the website</p>
	</div>
	<div class ="col-sm-3 col-xs-6 text-center">
		{% if not is_org %}
			<a href="{% url 'org-reg' %}" class="btn btn-warning" role="button">Register as Organizer</a></p>
		<p>Fill up the form to become an event organizer</p>
		{% else %}
			{# For organizer #}
			<a href="{% url 'org-update' %}" class="btn btn-warning" role="button">Edit my Org </a></p>
			<p>Edit your Organizer profile </p>
			{# ===== #}
			<a href="{{ current_org.get_absolute_url }}" class="btn btn-warning" role="button">Your page</a></p>
			<p>Check how does your page look like </p>
		{% endif %}
	</div>
	<div class ="col-sm-3 col-xs-6 text-center">
		<a href="{% url 'dashboard' %}" class="btn btn-success " role="button">Dashboard</a></p>
		<p>Go to Dashboard to manage your Events</p>
	</div>
	<div class ="col-sm-3 col-xs-6 text-center">
		<a href="{% url 'event-reg' %}" class="btn btn-primary" role="button">Publish event</a></p>
		<p>Publishing event form</p>
	</div>
</div></div>


	
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


{% endblock %}

core/templates/core/dashboard.html
{% extends "base.html" %}


{% block content %}

<div class="conteiner">
	<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
<h3>Your Events</h3>
<a href="{% url 'event-reg' %}" class="btn btn-primary" role="button">Register New Event</a></p>
<table class="table table-hover table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Active</th>
			<th>Public Link</th>
			<th>Edit</th>
		</tr>
	</thead>
	{% for event in events %}
	<tr>
		<th>{{ event.title }}</th>
		{% if event.is_published %}
		<th>Yes</th>
			{% else %}
		<th>No</th>
			{% endif %}
		<th><a href="{{ event.get_absolute_url }}">Link</a></th>
		<th><a href="{% url 'event-edit' event.id %}">Edit</a></th>

	</tr>
	{% endfor %}
</table>
</div>
</div>

<br><br>
<br>
<br>
<br>

{% endblock %}

core/templates/core/event-edit.html
{% extends "base.html" %}
{{ form.media }}
{% load crispy_forms_tags %}
{% block content %}

<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
<h2>Edit your event</h2><br>
<!--     <form id="form" method="post" action="{{ action }}" enctype="multipart/for-data"> -->
    <form id="form" method="post" action=" "  enctype="multipart/form-data">
    
    {% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}

    <input type="submit" name="submit" value="Submit" class="btn btn-primary">
    </form>

{% endblock %}

core/templates/core/event-reg.html
{% extends "base.html" %}
{{ form.media }}
{% load crispy_forms_tags %}

{% block content %}

<div class="conteiner">
	<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
	<h2>Event registration</h2><br>
	<form id="event_form" method="post" action="{% url 'event-reg' %}" enctype="multipart/form-data">
	{% csrf_token %}
	{{ event_form.media }}
	{{ event_form|crispy }}

	<input type="submit" name="submit" value="Register">
	</form>
	</div>
</div>
{% endblock %}

core/templates/core/event_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail%}


{% block menu %}
 {% include 'core/menu_custom.html' %}
{% endblock %}

{% block content %}

<title>{% block title %}{{event.title}}{% endblock %}</title>

<hr style="margin-top: 30px">

    <div class="container">
        <div id="event" class="grp-margin-left-xs">
            <div>
                {% if event.thumbnail %}
                    {% thumbnail event.thumbnail "150x100" crop="center" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" id="events_img_tn">
                    {% endthumbnail %}
                {% else %}    
                    <img class="img-responsive" src="{% static 'no-image-icn.png' %}">
                {% endif %}
                <h3><p>{{event.title_en}}</p></h3>
                <b><p>{{event.title_cn}}</p></b>
                <p><span class="glyphicon glyphicon-time" aria-hidden="true"></span><b> {{event.start_date|date:'Y-m-d'}}, {{event.start_time|date:'H:i'}}</b></p>
                <p class="text-right"><span class="glyphicon glyphicon-map-marker" aria-hidden="true" ></span> {{event.get_district_display}}</p>
                <p class="text-right"><span><strong>¥ </strong></span>{{ event.fee }}</p>
                <p class="text-right">{{event.location_cn}}</p>
                <p class="text-right">{{event.location_en}}</p>
                <p>{{event.content_en}}</p>
                <p>{{event.content_cn}}</p>
                <p class="text-right">Organized by: {{event.org}}</p>
                <b>Description</b>
                <p>{{event.richcontent|safe|escape }}</p>
                <hr>
                <p>Scan QR code to contact this activity's organizer</p>
                <p>扫描二维码,直接加组织者的微信'</p>
                {% if event.org.qr %}
                    <img class="img-responsive" src="{{event.org.qr.url}}" height="150" width="150">
                {% else %}
                    <img class="img-responsive" src="{% static 'no-image-icn.png' %}">
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

core/templates/core/events.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail%}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'my-css.css' %}">
</head>


<hr style="margin-top: 30px">

    <div class="container">
        <div class="row">

                <div class="panel panel-default widget" id="upcoming_events">
                    <div class="panel-heading">
                        <h3 class="panel-title">Upcoming events soon</h3>
                    </div>
                    <div class="panel-body" id="event_panel">
                        {% if upcoming_events %}
                            {% for event in upcoming_events %}
                                <div class="row list-group-item">
                                    <div class="row">
                                    <div class="col-xs-4">
                                        <a href="{{ event.get_absolute_url }}">
                                            {% if event.thumbnail %}
                                                {% thumbnail event.thumbnail "150x100" crop="center" as im %}
                                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" id="events_img_tn" class="img-responsive">
                                                {% endthumbnail %}
                                            {% else %}    
                                                <img class="img-responsive" src="{% static 'no-image-icn.png' %}">
                                            {% endif %}
                                        </a>
                                    </div>
                                    <div class="col-xs-8 ">
                                        <h4 id="events_title"><a href="{{ event.get_absolute_url }}">{{ event.title }}|{{event.title_cn}}</a></h4>
                                    </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-4" id="events_date">
                                            <p><span class="glyphicon glyphicon-time" aria-hidden="true"></span><b> {{event.start_date|date:'Y-m-d'}}, {{event.start_time|date:'H:i'}}</b></p>
                                        </div>
                                        <div class="col-xs-4" id="events_distr">
                                            <p class="text-right">
                                                <span class="glyphicon glyphicon-map-marker" aria-hidden="true" >
                                                </span> {{event.get_district_display}}
                                            </p>
                                        </div>
                                        <div class="col-xs-4" id="events_fee">
                                            <p class="text-right"><span><strong>¥ </strong></span>{{ event.fee }}</p>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 " id="events_content">
                                        <p>{{event.content_en|truncatewords:25}}<a href="{{ event.get_absolute_url }}"><small><u> more</u></small></a></p>
                                        <p>{{event.content_cn|truncatechars:50}}<a href="{{ event.get_absolute_url }}"><small><u> 更多</u></small></a></p>
                                        <p class="text-right">Organized by: {{event.org}}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
        </div>
    </div>

{% endblock %}

<!--<div id="past_events">-->
    <!--<h3 class="text-center ">Past events</h3>-->
    <!--<div class="row">-->
        <!--{% for event in past_events %}-->
            <!--<div class="col-md-3">-->
                <!--<img src="http://placehold.it/100x60" width="80%" />-->
                <!--<h4><a href="/{{ event.url }}/">{{ event.name }}</a><h4>-->
                <!--<h4>{{ event.date|date:"d M y" }}</h4>-->
                <!--<p><i>{{ event.district }}</i></p>-->
            <!--</div>-->

            <!--{% if forloop.counter|divisibleby:4 %}</div><div class="row">{% endif %}-->
        <!--{% endfor %}-->
    <!--</div>-->
<!--</div>-->

core/templates/core/home.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>

<body>

<a href="{% url 'auth_login' %}">Login.</a>
<br/>
<a href="{% url 'index' %}">Return to the homepage.</a>
<br/>
<p>Registration: <a href="{% url 'registration_register' %}">Reg.</a></p>
<br />
<p>{{ user }}</p>

</body>
</html>

core/templates/core/menu_custom.html
{% extends 'core/menu.html' %}
{% load staticfiles %}

{% block navbar %}
<div class="container">
				<ul class="nav navbar-nav navbar-right mobile-bar">
					<!--See all events with arrow-->
					<li>
						<a href="{% url 'events'%}" id="see-events-xs">
							<!--<span class="menu-icon fa fa-angle-left"></span>-->
							<span class="menu-icon">
								<i class="fa fa-arrow-left" aria-hidden="true"></i>
								<i class="fa fa-calendar" aria-hidden="true"></i>
								<span>See all events</span>
							</span>
							<span class="hidden-xs"><b>Events</b></span>
							<p>查看所有的活动</p>
						</a>
					</li>
					<li class="hidden-xs">
						<a href="#">
							<!--<span class="menu-icon fa fa-picture-o"></span>-->
							<span><b>Become an organizer</b></span>
							<p>活动组织者</p>
						</a>
					</li>
					<li class="hidden-xs">
						<a href="#">
							<!--<span class="menu-icon fa fa-info"></span>-->
							<span class="hidden-xs"><b>About SZMksz</b></span>
							<p class="hidden-xs">关于</p>
							<!--<span class="visible-xs">About</span>-->
						</a>
					</li>
					<li class="hidden-xs">
						<a href="#">
							<!--<span class="menu-icon fa fa-phone"></span>-->
							<span class="hidden-xs"><b>Contact Us</b></span>
							<p class="hidden-xs">联系我门</p>
							<!--<span class="visible-xs">Contact</span>-->
						</a>
					</li>
					<li class="visible-xs">
						<a href="#navbar-more-show">
							<span class="menu-icon fa fa-bars"></span>
							<span>More</span>
						</a>
					</li>
				</ul>
			</div>
{% endblock navbar %}

core/templates/core/org-reg.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{{ form.media }}
{% block content %}

<br>
<div class="container">
<div class="row">
    <div class="col-xs-10 col-sm-6 col-md-4 col-xs-offset-1 col-sm-offset-2 col-md-offset-3">

{% if registered %}
	<strong>Thank you for registration</strong>
	<a href="{% url 'index' %}">Return to the homepage.</a><br />{}
{% else %}
	<h3>Register here</h3>
    <hr>

	<form id="org_form" method="post" action="{% url 'org-reg' %}" enctype="multipart/for-data">
	{% csrf_token %}
    {{ org_form.media }}
	{{ org_form|crispy }}

    <div class="col-xs-5 col-sm-5 col-md-5">
	<input type="submit" name="submit" value="Register" class="btn btn-primary btn-block">
    </div>
	</form>
{% endif %}
</div></div></div>
{% endblock %}